#lang racket
;; Cost model making ADD very expensive to find alternatives
#hash((add . 1000)      ; Make ADD prohibitively expensive
      (sub . 1)
      (and . 1)
      (or . 1)
      (xor . 1)
      (sll . 1)
      (srl . 1)
      (sra . 1)
      (slt . 1)
      (sltu . 1)
      (addi . 1)
      (andi . 1)
      (ori . 1)
      (xori . 1)
      (slti . 1)
      (sltiu . 1)
      (slli . 1)
      (srli . 1)
      (srai . 1)
      (lui . 1)
      (auipc . 1)
      (mul . 4)
      (mulh . 4)
      (mulhu . 4)
      (mulhsu . 4)
      (div . 32)
      (divu . 32)
      (rem . 32)
      (remu . 32))